### ISSUE TITLE
ed25519 patch for Dropbear upstream LEDE upstream

### ISSUE THREAD

**Issue by aparcar** [pts/pts-dropbear#1]
@pts do you have a patch file for ed25519 support?
I'd like to use it in LEDE/OpenWrt. Here are already some [patches](https://github.com/openwrt/openwrt/tree/5ce38c486c525b28d9784f83e839537aa0149123/package/network/services/dropbear/patches) applied for other stuff.

**Comment by pts** [comment]
I haven't prepared separate .patch files. Feel free to create them by running `git diff` on my commits in this repo or on https://github.com/pts/dropbear-ptscrypto (which I've created for a pull request to upstream Dropbear).
